### ISSUE TITLE
Don't request root privs with --vm-type=kvm or --vm-type=podman

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/osc#1410]
`osc build --vm-type=podman` and `osc build --vm-type=kvm` work fine as regular users as well, i.e. `OSC_SU_WRAPPER= osc build --vm-type=foo`. osc should default to not elevate privileges if those parameters are used.

**Comment by dmach** [comment]
Looks like we should also make additional changes to osc:

Extend the list of supported values for the `build-type` config option in the documentation, because obs-build supports:
```
  --vm-type TYPE
              Use virtual machine instead of chroot
              TYPE is one of xen|kvm|uml|qemu|lxc|zvm|openstack|ec2|docker|pvm|nspawn
```

Rename `build_type` config option to `vm_type` (while keeping the config option name as is),
because `build_type` is ambiguous and is also used to determine if we're building spec, dsc, kiwi, ...

And obviously omit using the `su_wrapper` when building with `podman` or `kvm` as requested above.
