### ISSUE TITLE
osc sr -s should keep submit-messagee

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/osc#1575]
**Is your feature request related to a problem? Please describe.**
When superseding a submitrequest, it is cumbersome to keep or slightly modify the previous SR's submit message, thus discouraging users from updating their changes with extra fixes.

**Describe the solution you'd like**
`osc sr -s $ID`
should open $EDITOR pre-filled with the submit message from SR $ID so that a `:wq` re-uses it, but also allows changes.

**Additional context**
Idea was proposed by @e4t

**Comment by e4t** [comment]
Background: A lot of checks run as OBS bots *after* the request has been made. It is close to impossible to make sure there are no issues at the time a request is made. Thus, there is a high chance that a request needs to be redone. Since OBS has no way to update an existing request the only way to do this is to create one 'de novo'.  This involves gathering all the information that has been provided with the existing request again. 
It would therefore be helpful if the comment was filled with the description of (and possibly all comments to) the request that's to be superseded.

**Comment by dmach** [comment]
Makes perfect sense. I've submitted a PR that should fulfill this. Please take a look if it works for you.
