### ISSUE TITLE
... is not an osc package working copy

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/osc#1594]
**Describe the bug**
An older checkout of a project from build.opensuse.org cannot be updated with osc version 1.8.1. I get an error message that "... is not an osc package working copy"

**Versions**
- Operating system: openSUSE Leap 15.5
- Packages: osc-1.8.1-150500.411.1.noarch

**To Reproduce**

1. Unpack [testcase.zip](https://github.com/user-attachments/files/16065679/testcase.zip)
2. Enter unpacked directory, open a console and run `osc update`
3. See error

**Expected behavior**
The error message should not appear and the update should take place.

**Additional context**
- A comparison of the old directory with a current check-out results:
```
$ diff -r windows\:mingw\:snapshots.old/ windows\:mingw\:snapshots
Only in windows:mingw:snapshots/.osc: _osclib_version.
```
By copying the file `_osclib_version` into the old directory, the update command is successfully executed, which suggests that the current osc version does not take this case into account.

- The older checkout took place in January 2019.

**Comment by dmach** [comment]
Thanks for the report. It looks there was a time when osc was creating incorrect checkouts without `_osclib_version`.
There's a pending PR that fixes that: https://github.com/openSUSE/osc/pull/1590
Originally I was planning to close it without merging, thinking that it was a one-off problem.
It seems that the problem might be more widespread and it requires a fix rather than forcing users to run `osc repairwc` for each such directory.
