### ISSUE TITLE
osc rq show doesn't list comments to the request

### ISSUE THREAD

**Issue by pgajdos** [openSUSE/osc#171]
It would be nice to have an option to show comments to a request.

Use case: I have accepted request via cli but it had comments that would lead rather to decline.

Thank you

**Comment by jsegitz** [comment]
Please have a look, this is rather important for us

**Comment by marcus-h** [comment]
It should be fixed with commit dc32cde545d1f9ba1d21e2a93b2a85338123e657.

But I'm not sure if the comments are displayed in a "readable"
way.
Example output:

marcus@linux:~> osc rq show 339347
Request: #339347

  submit:       home:Marcus_H/test@87 -> home:Marcus_H/testxxx


Message:
x

State:   new        2015-10-16T21:38:04 Marcus_H
Comment: <no comment>

History: 2015-10-16T21:38:05 Marcus_H     Request created

Comments:
On 2015-10-16 21:38:48 UTC Marcus_H wrote:
foo

  On 2015-10-16 21:44:04 UTC Marcus_H wrote:
  asdf

    On 2015-10-19 09:58:11 UTC Marcus_H wrote:
    this is 
    a multi 
    line test 
    xxx

On 2015-10-16 21:44:39 UTC Marcus_H wrote:
asdf

  On 2015-10-19 09:58:22 UTC Marcus_H wrote:
  ok 
  ok

On 2015-10-19 09:58:32 UTC Marcus_H wrote:
foo bar 
foobar

marcus@linux:~>

If you want to give it a try, the unstable packages are currently building
in the devel:tools:scm project.
Suggestions/improvements are always welcome:)

**Comment by jsegitz** [comment]
not readable here in the comment, but readable enough on the command line. We usually just have some short notices there, so that is okay. Thank you for the quick reaction

**Comment by marcus-h** [comment]
On 2015-10-19 08:11:31 -0700, Johannes Segitz wrote:
> not readable here in the comment,

Hmm sorry... no idea why it is displayed this way (I just replied
via my email client so I didn't check how it is "formatted" on
github).

> but readable enough on the command line.
> We usually just have some short notices there, so that is okay.
> 
Ok.
