### ISSUE TITLE
osc fails if API server is IPv6 only

### ISSUE THREAD

**Issue by dm8tbr** [openSUSE/osc#246]
After a few years went back to toying around with OBS. So I set up a private instance. My environment comes with autoconfigured IPv6 and I only look into IPv4 if the service is otherwise *completely* broken.

``~/src/packaging/obs$ osc -A mer copypac  home:tbr:sailfish libevent home:tbr -t brf``
yielded:
`` [Errno -5] No address associated with hostname: 'https://api.ruecker.fi/source/home%3Atbr/libevent/_meta'``

Once I caved and manually assigned the machine a public IPv4 address and added it to DNS, osc immediately worked without issue.

I may look into the reasons/patching later, but right now lack the time to do so. I did want to log this publicly though. So this issue is up for grabs.

**Comment by adrianschroeter** [comment]
Did you add a IPv4 address meanwhile to the server?

Because my osc hangs here on connect to 140.211.166.21 atm

**Comment by dm8tbr** [comment]
> Once I caved and manually assigned the machine a public IPv4 address and added it to DNS, osc immediately worked without issue.

So, yes.

Feel free to use (api|build|download).bfst.de as testing targets. Same server, but without the 'A' entry, only 'AAAA' entry for the IPv6 address.

**Comment by marcus-h** [comment]
On 2016-11-15 10:43:38 -0800, Thomas B. Ruecker wrote:
> After a few years went back to toying around with OBS. So I set up a private instance. My environment comes with autoconfigured IPv6 and I only look into IPv4 if the service is otherwise *completely* broken.
> 
> ``~/src/packaging/obs$ osc -A mer copypac  home:tbr:sailfish libevent home:tbr -t brf``
> yielded:
> `` [Errno -5] No address associated with hostname: 'https://api.ruecker.fi/source/home%3Atbr/libevent/_meta'``
> 
Hmm I assume your dns just had a AAAA resource record for this domain
and _no_ A record. If so, this should be fixed in commit
3b3bb21645baa0d48e006ecbb6374dc040c01688. If you want to give it a try,
you can have a look at the devel:tools:scm/osc package (which is based
on osc's master branch and has the fix - note: this is no "official"
osc release).
So I think we can close issue (if it doesn't work for you, please
reopen).

**Comment by dm8tbr** [comment]
Yes, in the beginning there were only AAAA records. I'll try to test it soon. Thanks for addressing this!
