### ISSUE TITLE
osc ls and multibuild handling

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/osc#338]
Currently, osc ls doesn't handle multibuild like other osc commands, because -M is already used for --meta.

Moreover, it is tricky to get list of binaries for all the multibuild of a project. I have to use something like:
osc api/build/SUSE:SLE-15:GA/_result?package=000product&multibuild=1&repository=images&arch=local&view=binarylist'

and parse it to get list of all iso build for the product.

**Comment by nickbroon** [comment]
Are there any plans to add multibuild support to 'osc ls'?
multibuild is now widely used, but the basic osc ls command still lacks support for it which makes things very awkward.

**Comment by lethliel** [comment]
Yes. Now that the python3 port is done and the python3 version is quite stable I will start working on the other issues. 

One of the next issues will be definitively this.

**Comment by dmach** [comment]
Multibuild listing has been implemented already, but there seem to be some side-effects such as #1197.
Also, `osc ls` is supposed to work with sources, while multibuild packages are part of build results.
This means the behavior may change in the future in order to make it consistent and logical across all osc commands.
