### ISSUE TITLE
Not closing the SSL connection causes osc to hang in libcrypto

### ISSUE THREAD

**Issue by sriemer** [openSUSE/osc#384]
https://github.com/openSUSE/osc/blob/6b04a6584b50bce79820aab99882569ad5f3927b/osc/oscssl.py#L218-L224

osc requests that M2Crypto closes the SSL connection in `h.request()` due to `headers["Connection"] = "close"`. Then it uses it again to get the response. In fact, the connection isn't closed at all because of that. It has to be closed explicitly after getting the response.

For details see: https://bugzilla.opensuse.org/show_bug.cgi?id=1068470

Please remove `headers["Connection"] = "close"` here and call `h.close()` after getting the response.

https://github.com/openSUSE/osc/blob/6b04a6584b50bce79820aab99882569ad5f3927b/osc/oscssl.py#L300-L302

Please add the following here:
```python
    def close(self):
        self.sock.close()
```

**Comment by sriemer** [comment]
OMG, blame shows that this is broken since 7 years.

**Comment by marcus-h** [comment]
On 2018-02-22 17:49:21 +0000, Sebastian Parschauer wrote:
> https://github.com/openSUSE/osc/blob/6b04a6584b50bce79820aab99882569ad5f3927b/osc/oscssl.py#L218-L224
> 
> osc requests that M2Crypto closes the SSL connection in `h.request()` due to `headers["Connection"] = "close"`. Then it uses it again to get the response. In fact, the connection isn't closed at all because of that. It has to be closed explicitly after getting the response.
> 
> For details see: https://bugzilla.opensuse.com/show_bug.cgi?id=1068470
> 
> Please remove `headers["Connection"] = "close"` here and call `h.close()` after getting the response.
> 
Just a few quick remarks (I need to have a further look at it):
- headers["Connection"] = "close" does not imply that the connection is
  closed (m2urllib2.HTTPSConnection.close is a NOP)
- Sending the "Connection: close" header is required by the HTTP 1.1
  protocol (since we do not want to have a persistent connection); Hence,
  we should not omit this header
- This does not seem to be a use-after-free (as in the subject), but
  rather some kind of fd leak (since, as you said, the connection is
  not properly closed)
- The "self.saved_session" codepath in osc.myHTTPSHandler might look
  a bit suspicious (I need to have a look at it)

There seem to be 2 culprits (one in osc and one in M2Crypto):
- The copied code in osc.myHTTPSHandler.https_open does the following: 

  fp = socket._fileobject(r)

  Calling fp.close() (which is indirectly called through the addinfourl
  object) is a NOP (except a flush()). We should use

  fp = socket._fileobject(r, close=True)

  (I just checked the recent M2Crypto code and that's what it also
  does). However, that's not sufficient, because a fp.close()
  still won't close the connection, because h.fp (h is a
  httplib.HTTPResponse instance) is again wrapped in a
  socket._fileobject that was created with close=False
  (see httplib.HTTPResponse.__init__ and
  M2Crypto.SSL.Connection.makefile)

- In the same vein, M2Crypto.m2urllib.HTTPSHandler.https_open is
  affected: the SSL.Connection is not properly closed, because
  calling close() on the addinfourl instance, which is returned
  by https_open, is a "NOP".

Btw., are you behind a proxy? I'm wondering why this bug has such
an impact on your system (I never saw a bug report similar to this
one).

Does the attached patch work for you?


diff --git a/osc/oscssl.py b/osc/oscssl.py
index 7aa5a0d..21130eb 100644
--- a/osc/oscssl.py
+++ b/osc/oscssl.py
@@ -238,13 +238,19 @@ class myHTTPSHandler(M2Crypto.m2urllib2.HTTPSHandler):
         # out of socket._fileobject() and into a base class.
 
         r.recv = r.read
-        fp = socket._fileobject(r)
+        fp = socket._fileobject(r, close=True)
 
         resp = addinfourl(fp, r.msg, req.get_full_url())
         resp.code = r.status
         resp.msg = r.reason
         return resp
 
+
+class MySSLConnection(SSL.Connection):
+    def makefile(self, mode='rb', bufsize=-1):
+        return socket._fileobject(self, mode, bufsize, close=True)
+
+
 class myHTTPSConnection(M2Crypto.httpslib.HTTPSConnection):
     def __init__(self, *args, **kwargs):
         self.appname = kwargs.pop('appname', 'generic')
@@ -254,14 +260,14 @@ class myHTTPSConnection(M2Crypto.httpslib.HTTPSConnection):
         # workaround for old M2Crypto versions where the the
         # SSL.Connection.__init__ constructor has no "family" parameter
         kwargs = {}
-        argspec = inspect.getargspec(SSL.Connection.__init__)
+        argspec = inspect.getargspec(MySSLConnection.__init__)
         if 'family' in argspec.args:
             kwargs['family'] = family
         elif family != socket.AF_INET:
             # old SSL.Connection classes implicitly use socket.AF_INET
             return False
 
-        self.sock = SSL.Connection(self.ssl_ctx, **kwargs)
+        self.sock = MySSLConnection(self.ssl_ctx, **kwargs)
         if self.session:
             self.sock.set_session(self.session)
         if hasattr(self.sock, 'set_tlsext_host_name'):

**Comment by mcepl** [comment]
BTW, just let me note that
```python
fp = socket._fileobject(r)
```
is digging into unsupported interfaces. ``socket._fileobject()`` is not part of the supported API, and it could go away any time.

**Comment by marcus-h** [comment]
On 2018-02-22 14:50:18 -0800, Matěj Cepl wrote:
> BTW, just let me note that
> ```python
> fp = socket._fileobject(r)
> ```
> is digging into unsupported interfaces. ``socket._fileobject()`` is not part of the supported API, and it could go away any time.
> 
Yep, but that's what M2Crypto.m2urllib.HTTPSHandler.https_open does
and we just copied + slightly adapted the code. We could avoid the
copy if we directly "modify" the M2Crypto.httpslib.*HTTPSConnection
classes, but that's also "ugly"... Nevertheless, we would also
hit the M2Crypto "issue" that I outlined above.

**Comment by mcepl** [comment]
> is digging into unsupported interfaces. socket._fileobject() is not part of the supported API, and it could go away any time.

M2Crypto provides ``makefile`` method, which is, and remains supported even with py3k (see tests for illustration, how to use it). Of course, I was stupid, because ``socket._fileobject()`` is not part of M2Crypto, but of Python 2; nevertheless, it really is not documented, and it will really go away in py3k.

**Comment by sriemer** [comment]
What I couldn't test so far is if `h` is the Proxy connection. `headers["Connection"] = "close"` definitely does something. If I use `h.close()` even at the end of the function, then I get this:
`IncompleteRead(0 bytes read)`

I guess it causes that the server closes the connection but that is not what we want. We want to close the connection with `SSL_shutdown()` for complete SSL communication and no RSTs which is exactly what `self.sock.close()` calls.

**Comment by sriemer** [comment]
Commit 0ddb598743a5be82fe9790f87e892976e1ca9c6d is broken as it still calls:
`headers["Connection"] = "close"`
and doesn't add the missing `close()` method. Don't you test your commits?

**Comment by marcus-h** [comment]
On 2018-02-23 09:44:36 +0000, Sebastian Parschauer wrote:
> What I couldn't test so far is if `h` is the Proxy connection. `headers["Connection"] = "close"` definitely does something. If I use `h.close()` even at the end of the function, then I get this:
> `IncompleteRead(0 bytes read)`
> 
Are you using a proxy?

**Comment by sriemer** [comment]
Nope, not using a proxy but `h` can be of type `myHTTPSConnection` for which I have a fix or of type `myProxyHTTPSConnection` for which I don't know how to test it.

Can you provide me hints how to test the `myProxyHTTPSConnection` class?

**Comment by marcus-h** [comment]
On 2018-02-23 05:38:28 -0800, Sebastian Parschauer wrote:
> Nope, not using a proxy but `h` can be of type `myHTTPSConnection` for which I have a fix or of type `myProxyHTTPSConnection` for which I don't know how to test it.
> 
Ok.
How does your fix look like?
Does the patch from my first mail work for you?

> Can you provide me hints how to test the `myProxyHTTPSConnection` class?
> 
Let's do this later.

**Comment by sriemer** [comment]
No, changing `fp = socket._fileobject(r)` to `fp = socket._fileobject(r)` does not help.

But I've noticed that it is already enough to add the `close()` method to class `myHTTPSConnection` like this:
```python
     def close(self):
         self.sock.close()
```
Then it is called automatically and no RSTs are visible in the tcpdump.

**Comment by sriemer** [comment]
Sorry, missed the rest of your patch. Yes, your patch works. No RSTs in the tcpdump. Thanks.

**Comment by sriemer** [comment]
Btw. I'm located in Berlin, my provider is Vodafone/Kabeldeutschland, and I have approx. 30ms latency to the servers in Nuremberg. I've noticed this bug with a Tumbleweed VM via LAN first. Then I've verified with a physical system and connected my Laptop directly to the cable modem which showed that Tumbleweed is affected there only with IPv4 and not IPv6 but the RSTs were always visible in a tcpdump. With WiFi and a bigger variety of ping latency I was also able to trigger this on openSUSE Leap 42.3. The client hello of the next file hasn't been sent to the server and osc was waiting for the server hello in libcrypto while the client hello has been cyclic retransmitted but ignored on the server.

This is it regarding the history how I've noticed this bug and how it blocked me developing my code for openSUSE:Factory.

**Comment by mcepl** [comment]
Looking at the troubles with this issue, let me suggest https://gitlab.com/m2crypto/m2crypto/merge_requests/184 . I plan to do new small release of M2Crypto soon, so if you could take a look and comment on this, you would have SSL.Connection.Connection as a context manager, and I believe your life would be better. Context managers are the right thing to make resources management in Python semiautomatic (not destructors, as was originally suggested).

**Comment by marcus-h** [comment]
On 2018-02-24 04:37:09 -0800, Matěj Cepl wrote:
> Looking at the troubles with this issue, let me suggest https://gitlab.com/m2crypto/m2crypto/merge_requests/184 . I plan to do new small release of M2Crypto soon, so if you could take a look and comment on this, you would have SSL.Connection.Connection as a context manager, and I believe your life would be better. Context managers are the right thing to make resources management in Python semiautomatic (not destructors, as was originally suggested).
> 
@mcepl: First of all, thanks a lot for your support! Unfortunately,
this won't really help. Actually, the way we use m2crypto is something
like this:

```python
#!/usr/bin/python

import socket
from M2Crypto import m2urllib2, SSL


OrigSSLConnection = SSL.Connection


class MySSLConnection(OrigSSLConnection):
    def close(self, *args, **kwargs):
        return OrigSSLConnection.close(self, *args, **kwargs)

    def makefile(self, *args, **kwargs):
        # python2 only...
        kwargs['close'] = True
        return socket._fileobject(self, *args, **kwargs)


# If you comment the next line, the connection is _NOT_ closed
SSL.Connection = MySSLConnection

# The following is our actual (simplified) usage pattern:

opener = m2urllib2.build_opener()
f = opener.open('https://api.opensuse.org/public/source/home:Marcus_H/xxx/testfile')
# do something useful...
f.close()
```

That is, the SSL.Connection instance is solely managed by the M2Crypto
code. The problem is that "f.close()" does not yield to a close() of the
SSL.Connection instance. With the above "SSL.Connection = MySSLConnection"
hack, the MySSLConnection instance is properly closed when doing
"f.close()".
IMHO, this seems to be an issue with M2Crypto - what do you think?

**Comment by mcepl** [comment]
OK, this is probably a way above fixing one stupid bug, but I have to admit that I don't like this at all. Monkey-patching on code which has behind itself rather brittle C monster build by Swig, seems like a recipe for disaster.

Could I ask what actually you want to achieve, what’s the point why you just cannot use plain ``m2urllib`` (or ``m2urllib2``, or to be honest even plain ``ssl`` from the standard library)?

**Comment by marcus-h** [comment]
On 2018-02-24 22:43:52 +0000, Matěj Cepl wrote:
> OK, this is probably a way above fixing one stupid bug, but I have to admit that I don't like this at all. Monkey-patching on code which has behind itself rather brittle C monster build by Swig, seems like a recipe for disaster.
> 
Naw, this was just meant to illustrate the problem.

> Could I ask what actually you want to achieve, what’s the point why you just cannot use plain ``m2urllib`` (or ``m2urllib2``, or to be honest even plain ``ssl`` from the standard library)?
> 
Just consider the following code:

```python
opener = m2urllib2.build_opener()
f = opener.open('https://api.opensuse.org/public/source/home:Marcus_H/xxx/testfile')
# do something useful...
f.close()
```

In this case M2Crypto internally creates a SSL.Connection instance
that is never close()d. That's what this bug is basically about.

**Comment by mcepl** [comment]
Oh, right, so this is actually RFE to get the context manager functionality for ``m2urllib2.opener``? That's a good idea, I will add it to that merge request above.

**Comment by mcepl** [comment]
@marcus-h OK, I welcome comments on https://gitlab.com/m2crypto/m2crypto/merge_requests/185

**Comment by marcus-h** [comment]
On 2018-02-26 14:37:12 +0000, Matěj Cepl wrote:
> @marcus-h OK, I welcome comments on https://gitlab.com/m2crypto/m2crypto/merge_requests/185
> 
@mcepl: Hmm there are two potential "issues" with this solution.
The following remarks apply to python 2.7.14 (I haven't checked the
corresponding python3 code yet).

If a server does not send a "Connection: close" header, then
HTTPSConnection.close is never called (assuming a HTTP/1.1 request).
If I understand rfc7230 [1] correctly, a server is not required to
include a "Connection: close" header in its response if the
corresponding client request already contained a "Connection: close"
header.

The other "issue" is that we might perform the SSL_shutdown(...)
too early. If the server's response includes the "Connection: close"
header, HTTPSConnection.close is called _before_ we read the message
body. This causes an issue if the server reacts with a SSL_shutdown(...)
to our close_notify alert _before_/_during_ the transmission of the
message body (this behavior is IMHO compliant with rfc5246 [2]). In
this case, we might not be able to receive the complete message
body... (debugging such a situation can be quite "challenging")

I'm still in favor of the following:

- Create a MySSLConnection class in m2urllib2, which inherits from
  SSL.Connnection (it just overrides the makefile(...) method
  (see MySSLConnection in an earlier post))
- Pass this class to httpslib.HTTPSConnection/ProxyHTTPSConnection
  in m2urllib2.HTTPSHandler.https_open
- Adjust httpslib.HTTPSConnection so that the passed class is used in
  httpslib.HTTPSConnection.connect
  (A similar adjustment is needed in ProxyHTTPSConnection._start_ssl)

Advantage: SSL_shutdown(...) is performed when the user calls
close() on the addinfourl instance, which avoids the two issues.

If you like, I can try to come up with a patch for this (basically,
I have one ready where the python3 bits are missing).

What do you think?


[1] https://tools.ietf.org/html/rfc7230#page-51
[2] https://tools.ietf.org/html/rfc5246#section-7.2.1

**Comment by mcepl** [comment]
> If you like, I can try to come up with a patch for this (basically, I have one ready where the python3 bits are missing).

Let me see it, please. You are right, after reanalyzing what's going on, my patch is meaningless. And yes, wrapping ``addinfourl`` is probably the best way.

**Comment by mlschroe** [comment]
Hmm, why don't you implement that _makefile_refs counting like in python's ssl.py?

**Comment by marcus-h** [comment]
On 2018-02-27 18:53:52 +0000, Matěj Cepl wrote:
> > If you like, I can try to come up with a patch for this (basically, I have one ready where the python3 bits are missing).
> 
> Let me see it, please. You are right, after reanalyzing what's going on, my patch is meaningless. And yes, wrapping ``addinfourl`` is probably the best way.
> 
Here we go https://gitlab.com/m2crypto/m2crypto/merge_requests/188

**Comment by marcus-h** [comment]
On 2018-02-28 10:25:18 +0000, Michael Schroeder wrote:
> Hmm, why don't you implement that _makefile_refs counting like in python's ssl.py?
> 
That's what my PR/MR is basically doing (in a way that works with
python2 and python3).

**Comment by sriemer** [comment]
In case somebody else finds this:
This is still broken in Leap 15.2. The fix is in: https://build.opensuse.org/project/show/home:TuxCheater:leap15.2_fixes
```diff
Index: b/osc/oscssl.py
===================================================================
--- a/osc/oscssl.py
+++ b/osc/oscssl.py
@@ -306,6 +306,10 @@ class myHTTPSConnection(M2Crypto.httpsli
     def getPort(self):
         return self.port
 
+    # boo#1068470 - sparschauer hack
+    def close(self):
+        self.sock.close()
+
 class myProxyHTTPSConnection(M2Crypto.httpslib.ProxyHTTPSConnection, HTTPSConnection):
     def __init__(self, *args, **kwargs):
         self.appname = kwargs.pop('appname', 'generic')
```
Let's hope that proper SSL handling is more important for `osc2`.

Closing as a `WONTFIX`.
