### ISSUE TITLE
keyring usage and empty passwords

### ISSUE THREAD

**Issue by frispete** [openSUSE/osc#418]
Hi,

after upgrading python-keying in my [repo](https://build.opensuse.org/package/show/home:frispete:python/python-keyring), keyring will finally prefer kwallets over SecretService within KDE. (yay!)

While at it, I attempted to clean up/improve osc keyring [usage](https://github.com/frispete/osc/commit/d11fa47ee9a8a079bc58e99f685f023eb58c5fe4), but stumbled across a strange handling of  empty users/passwords in osc. When cancelling the password dialog, kwallets return None¹, resulting in osc to spit:
```
no password defined for "https://api.opensuse.org".
Please fix your keyring entry or gnome-keyring setup.
Assuming an empty password.

```
Is this feature of empty users/passwords really used somewhere? 
What's the rational of this?

¹) This is another issue being worked on [here](https://github.com/frispete/keyring/commit/1bc7402af193aeb9d344f96cf1d789add44df9ca)

**Comment by marcus-h** [comment]
On 2018-05-15 16:17:06 -0700, Hans-Peter Jansen wrote:
> after upgrading python-keying in my [repo](https://build.opensuse.org/package/show/home:frispete:python/python-keyring), keyring will finally prefer kwallets over SecretService within KDE. (yay!)
> 
You can configure the default keyring backend in
~/.local/share/python_keyring/keyringrc.cfg.

> While at it, I attempted to clean up/improve osc keyring [usage](https://github.com/frispete/osc/commit/d11fa47ee9a8a079bc58e99f685f023eb58c5fe4), but stumbled across a strange handling of  empty users/passwords in osc. When cancelling the password dialog, kwallets return None¹, resulting in osc to spit:
> ```
> no password defined for "https://api.opensuse.org".
> Please fix your keyring entry or gnome-keyring setup.
> Assuming an empty password.
> 
> ```
> Is this feature of empty users/passwords really used somewhere? 
> What's the rational of this?
> 
No, it is not a feature. It was supposed to handle the case where
the password returned from the keyring is None (that is, interpreting
None as the empty password) (since commit
9561a99d6ba62d3fcfce262e359ba31ce78e2fa7, this is dead code (if the
keyring returns None, it is interpreted as the password "None",
which is not really helpful...)). In short: we should probably
restore the "original" behavior (None implies empty password) or
raise an exception.

**Comment by frispete** [comment]
Thanks @marcus-h for the feedback.

> You can configure the default keyring backend in ~/.local/share/python_keyring/keyringrc.cfg.

Sure, I'm rather referring to the OOB experience here...

> In short: we should probably restore the "original" behavior (None implies empty password) or raise an exception.

Yes, that was my impression as well, thanks. 

On the keyring side, we're going to improve the kwallet behaviour with the next release.

Will prepare a MR and we can discuss further issues there.
