### ISSUE TITLE
user name case difference returns an unexpected error when using requestmaintainership

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/osc#434]
When requesting maintainership for a package without specifying the username, osc is supposed to use the current username. However it is not using the server-side username, but the one locally specified in `.oscrc`.

From `osc help requestmaintainership`:

```
osc requestmaintainership                            # for current user in checked out package
[...]
 osc requestmaintainership PROJECT PACKAGE            # for current user
```

If the casing of the username in .oscrc differs from the casing of the username server-side, all operations will work, except for this fallback. The message given is: "No such username: InCoRrEct CaSiNg"

**Comment by marcus-h** [comment]
On 2018-07-24 04:10:59 -0700, Andreas Stieger wrote:
> When requesting maintainership for a package without specifying the username, osc is supposed to use the current username. However it is not using the server-side username, but the one locally specified in `.oscrc`.

<SNIP>

> If the casing of the username in .oscrc differs from the casing of the username server-side, all operations will work, except for this fallback. The message given is: "No such username: InCoRrEct CaSiNg"
> 
Yes, that's the correct behavior. The username in the .oscrc should
agree with the username that is stored in the frontend. It seems that
ichain/whatever is used nowadays seems to be case insensitive wrt.
to the username (that's why the authentication works). However, the
frontend is not case insensitive. For instance,
"osc meta user iNcoRrEcT cAsInG" should also fail.

Now, what's really really "stupid" (IMHO) is the following: it seems
that ichain is case insensitive wrt. exactly one char in the password

curl -u Marcus_H:mypass https://api.opensuse.org/source/home/Marcus_H/xxx
and
curl -u Marcus_H:myPass https://api.opensuse.org/source/home/Marcus_H/xxx

work, while

curl -u Marcus_H:myPasS https://api.opensuse.org/source/home/Marcus_H/xxx

does not work...

**Comment by marcus-h** [comment]
Closing as "invalid" (if you disagree, please reopen).
