### ISSUE TITLE
osc meta attribute openSUSE:Factory -a ATTR -e -> no edit option

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc#435]
According to osc --help, one should be able to edit an attribute using meta attribute -e;

This though results in a NO-OP, no editor showing up.

Calling the command ```osc -d meta attribute openSUSE:Factory -a OSRT:Config -e``` does not show a single API call being done

**Comment by lethliel** [comment]
This is not that easy. 

-e results in a PUT that uploads the resulting XML to the server. 

But for attributes there is no PUT route, because every attribute can have different 
permissions (and thus is completely different to other meta files like project meta)

What I can do is add a edit mode for single attributes. 

Like:
`osc meta attribute home:mstrigl -e -a OBS:RejectRequests`

And then a editor shows up for just this attribute. 

And from the help: 

```
Usage:

    [SNIP]

    osc meta attribute PRJ [PKG [SUBPACKAGE]] [--attribute ATTRIBUTE] [--create [--set <value_list>]|--delete|--set <value_list>]

```

**Comment by DimStar77** [comment]
> What I can do is add a edit mode for single attributes.
>
>Like:
>osc meta attribute home:mstrigl -e -a OBS:RejectRequests

Single attribute editing would be helpful in this case, indeed

**Comment by SchoolGuy** [comment]
I got hit by this today since the Python code for this is directly in the CLI and not accessible through the Python API. Thus I need to duplicate this code now into openSUSE-release-tools. It would really be nice if [this](https://github.com/openSUSE/open-build-service/issues/7839) will be implemented soon. I can't write Ruby, so I sadly can't contribute this, however I could fix `osc` if the server side code is existing.
