### ISSUE TITLE
osc sr ignores commandline options

### ISSUE THREAD

**Issue by olafhering** [openSUSE/osc#445]
Creating a submit request in some project, targeted for another. The intention on the commandline is clear, the target API host is not the one in `.osc/_apiurl`:

```
$ ibs sr  SUSE:SLE-12-SP4:GA
created request id 637890
```
Actual result: [https://build.opensuse.org/request/show/637890](url)

Expected result: some error that current pkg can not directly operate with `-A $url`
```
$  cat $(type -P ibs)
#/bin/sh
export OSC_CONFIG=$HOME/.osc/oscrc
exec /usr/bin/osc --config=$OSC_CONFIG -A https://api.suse.de "$@"
```

**Comment by marcus-h** [comment]
On 2018-09-25 09:12:13 +0000, Olaf Hering wrote:
> Creating a submit request in some project, targeted for another. The intention on the commandline is clear, the target API host is not the one in `.osc/_apiurl`:
> 
> ```
> $ ibs sr  SUSE:SLE-12-SP4:GA
> created request id 637890
> ```
> Actual result: [https://build.opensuse.org/request/show/637890](url)
> 
> Expected result: some error that current pkg can not directly operate with `-A $url`

Hmm no that's the "expected" behavior because the "sr" command is
(partially) context sensitive. That is, if cwd is a project or
package working copy, it will try to retrieve the information
(including the apiurl) from the working copy.
The same holds for other context sensitive commands. For instance,
"cd pkg_wc; osc -A xyz ci" will commit to the api that is specified
in pkg_wc.
