### ISSUE TITLE
osc submitrequest should accept all kinds of revisions

### ISSUE THREAD

**Issue by johanneskastl** [openSUSE/osc#468]
Currently `osc submitrequest -r` needs to be called with the revision of the expanded sources, see [this mail](https://lists.opensuse.org/opensuse-buildservice/2018-11/msg00016.html) on the buildservice list.

It would be great if any of the other revision "descriptors" would work. I.e. the one you get from `osc log` that reads `r7`, or the plain number (as can be seen on the Revisions tab of the package in the WebUI)  or the hash that also is given in `osc log`.

**Comment by johanneskastl** [comment]
Hi Marcus,

sorry, you lost me there. ;-)

In my (simple) case nothing other than the buildhist revisions did work. I would not call that "revisions are already supported". It seems to me like the job to find out which exact "correct revision" I need when I say "take revision 7" is something that osc should do, not me. 

Kind regards,
Johannes

**Comment by johanneskastl** [comment]
Adrian, I could successfully checkout the revisions I wanted to submit. I saw no errors and no conflicts. That was the first thing I tried.

So, I'm puzzled. Do you actually mean "our revision" (somewhere inside OBS or something) or did you want to say "your revision" (aka the package in `home:ojkastl_buildservice:...`?

**Comment by adrianschroeter** [comment]
at least the mentioned revision 7 from your revision has an expansion error:

```
# osc api /source/home:ojkastl_buildservice:Branch_Virtualization_vagrant/vagrant?rev=7
<directory name="vagrant" rev="7" vrev="7" srcmd5="7dc081528e717bbe3f1c2f9c77cbebb0">
  <linkinfo project="Virtualization:vagrant" package="vagrant" baserev="02db93e63a7b53d65ede64c657288ded" xsrcmd5="267ab3e3fe08bab816667de195b522b5" error="conflict in file vagrant.spec" />
...
```

**Comment by adrianschroeter** [comment]
btw, we could support non fixed (or not versioned) revisions in requests in osc (api is supporting this). But openSUSE submissions would be refused automatically, since they are against the policy there (review must happen on fixed sources).

**Comment by johanneskastl** [comment]
Hi Adrian, yes, now it has errors, as I submitted several revisions of the package with Andreas' workaround. I just tested, I can no longer check out those revisions, which worked fine when I sent the mail. Believe me, that was the first thing I tried.

I have no clue what "non fixed (or not versioned)" are, I would just like to have osc do the magic, so that a simple `osc sr -r 7 -m "here it is"` would work.

**Comment by adrianschroeter** [comment]
On Montag, 19. November 2018, 08:50:31 CET Johannes Kastl wrote:
> Hi Adrian, yes, now it has errors, as I submitted several revisions of the
> package with Andreas' workaround. I just tested, I can no longer check out
> those revisions, which worked fine when I sent the mail. Believe me, that
> was the first thing I tried.
> 
> I have no clue what "non fixed (or not versioned)" are, I would just like to
> have osc do the magic, so that a simple `osc sr -r 7 -m "here it is"` would
> work.

okay, I don't understand your problem then. It just works for me:

# osr -r1 home:adrianSuSE build home:adrianSuSE WEG
Warning: failed to fetch meta data for 'home:adrianSuSE' package 'WEG' (new 
package?) 
created request id 650119
# osc api /request/650119
<request id="650119" creator="adrianSuSE">
  <action type="submit">
    <source project="home:adrianSuSE" package="build" rev="1"/>
    <target project="home:adrianSuSE" package="WEG"/>
  </action>
  <state name="new" who="adrianSuSE" when="2018-11-19T08:00:07">
    <comment/>
  </state>
  <description>test</description>
</request>


-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de

**Comment by johanneskastl** [comment]
It did not work in my case. And I tried multiple revisions, with and without the "r", tried the md5sums from osc log, ...

And: I did not create a new package, as you just did in your example.

Marcus pointed out that it might or might not work:
> will work if the branch target hasn't changed. However, if it changed, r<NUM> or a srcmd5 might still work.

**Comment by adrianschroeter** [comment]
yes, but this is about the possible broken state due to merge conflicts. This has nothing to do with osc, it is just reality that you can create merge conflicts that way, if the link target is moving.

Or do you want that osc re-writes the revision for you? Would be an extra option, since we should not modify the user will on purpose (not sure if this will be understandable to many though)

**Comment by johanneskastl** [comment]
Adrian, why did `osc sr -r 0bde7ba11784dc0e0cac3efd019a12ba ...` work flawlessly while `osc sr -r r6 ` did not?

Or `osc sr -r 2e30355c7293a400ad189b1571497b67` (working) vs. `osc sr -r r7` or `osc sr -r 7`?

**Comment by adrianschroeter** [comment]
On Montag, 19. November 2018, 09:15:51 CET Johannes Kastl wrote:
> Adrian, why did `osc sr -r 0bde7ba11784dc0e0cac3efd019a12ba ...` work
> flawlessly while `osc sr -r r6 ` did not?
> 
> Or `osc sr -r 2e30355c7293a400ad189b1571497b67` (working) vs. `osc sr -r r7`
> or `osc sr -r 7`?

The error message points to a conflict. I doubt that you can show me an 
example where "osc co -r $rev -e ..." is working, but the same revision
does not in a submit request ....

Can you?

-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de

**Comment by johanneskastl** [comment]
As I said, there was no conflict, at least I had not seen any while checking out the revisions (with -e). And no, I can no longer reproduce this, as the vagrant package has been updated (which was the whole point in the first case).

I can have an eye out for these kind of changes and provide a test case, if one comes up.

**Comment by marcus-h** [comment]
On 2018-11-18 10:46:54 -0800, Johannes Kastl wrote:
> sorry, you lost me there. ;-)
> 
Hmm yes... I wasn't really explicit in my previous mail, sorry.

> In my (simple) case nothing other than the buildhist revisions did work.

A branch/link is not a "simple" case. A simple case is a plain package (no
branch/link whatever) :) (IMHO)

> I would not call that "revisions are already supported".

See below. In the following example, "osc sr -r4 prj1 A prj1" works.

> It seems to me like the job to find out which exact "correct revision" I need when I say "take revision 7" is something that osc should do, not me. 
> 
osc cannot infer from "take revision 7" the "intended" expanded rev. Let
me try to illustrate this a bit:

Let's assume prj1/A is a plain package (no branch/link) and prj2/B is
a branch of prj1/A. That is, it has a _link file that looks like this

<link project="prj1" package="A" baserev="r5">
  <patches>
    <branch/>
  </patches>
</link>

For convenience, in the following, A is used to denote package prj1/A
and B is used to denote package prj2/B (that is, if we know the package,
the project is implicitly known as well).

Next, consider for both packages the following "revision timeline".

----------------------- time ------------------------------------------------->

A: r4 --- r5 --------- r6 --- r7 --- r8 --- r9 --- r10 ------ r11 -- r12 -- r13
           ^                                        ^
           |------                                  |-----
                 |                                       |
B:               r1 -------------------------------------r2


Moreover, let t(pkg, rN) denote the time when revision rN was committed
to package pkg. That is, the figure from above yields the following
ordering wrt. to time:

t(A, r4) < t(A, r5) < t(B, r1) < t(A, r6) < t(A, r7) < t(A, r8) < t(A, r9)
    < t(A, r10) < t(B, r2) < t(A, r11) < t(A, r12) < t(A, r13)

Also, let br(pkg, rN) denote the baserev pointer of the branch package pkg
in revision rN. That is, we have

br(B, r1) = (A, r5) and br(B, r2) = (A, r10)

Additionally, lr(pkg) denotes the latest (or head) revision of the package
pkg. That is, we have

lr(A) = (A, r13) and lr(B) = (B, r2)


#
# Intermezzo: Expanding a branch (whose branch target is a plain package)
#

Next, let's have a brief look at expanding a branch. In general, to expand
a package three revisions are required: the revision of the branch package,
the baserev, and a linkrev. Let's assume we want to expand B in revision r2
and the _link file of B in r2 looks like this:

<link project="prj1" package="A" baserev="r10">
  <patches>
    <branch/>
  </patches>
</link>

For expanding B in r2, we need the following revision:

- (B, r2): this contains the _link file and other files
- br(B, r2) = (A, r10): the baserev
- lr(A) = (A, r13): the linkrev (see remark below)

Now, in essence, the expanded sources are just the 3-way merge of the sources
of (B, r2), br(B, r2), and lr(A). For instance, assume the file "foo" is
present in all three revisions. Then, in the expanded sources, the contents
of the file "foo" is given by

diff3 -m file(foo, (B, r2)) file(foo, br(B, r2)) file(foo, lr(A))

where file(foo, (pkg, rev)) denotes the path to file "foo" in package "pkg"
in revision "rev" (diff3 is provided by the diffutils package).

Note: an expand error can occur, for instance, if such a diff3 call fails
(that is, diff3 is unable to merge these files due to conflicts).

In the following, we say a

merge((B, rN), (A, rM), (A, rP)) conflicts iff the 3-way merge of
(B, rN), (A, rM), (A, rP) failed

and

merge((B, rN), (A, rM), (A, rP)) is OK iff
    not(merge((B, rN), (A, rM), (A, rP)) conflicts)



Remark:
In general, the linkrev depends on the _link file. That is, if our _link
would look like this

<link project="prj1" package="A" baserev="r10" rev="r11">
  <patches>
    <branch/>
  </patches>
</link>

then, the linkrev would be (A, r11). That is, if no "rev" attribute is
present in the _link file, the latest rev lr(A) is used.

#
# End of intermezzo
#

Let's get back to our scenario. Since our _link file has no "rev" attribute
the linkrev is always the latest revision. Assume we have the following
situation:

merge((B, r2), (A, r10), (A, r13)) = merge((B, r2), br(B, r2), lr(A)) is OK
merge((B, r2), (A, r10), (A, r12)) conflicts
merge((B, r2), (A, r10), (A, r11)) is OK
merge((B, r2), (A, r10), (A, r10)) is OK     (*)

(*): merging with linkrev = baserev is always OK.


merge((B, r1), (A, r5), (A, r13)) conflicts
merge((B, r1), (A, r5), (A, r12)) conflicts
merge((B, r1), (A, r5), (A, r11)) is OK
merge((B, r1), (A, r5), (A, r10)) conflicts   (**)
merge((B, r1), (A, r5), (A, r9))  is OK
merge((B, r1), (A, r5), (A, r8))  is OK
merge((B, r1), (A, r5), (A, r7))  conflicts
merge((B, r1), (A, r5), (A, r6))  is OK
merge((B, r1), (A, r5), (A, r5))  is OK       (see (*) above)

(**): that is, the conflict was resolved in (B, r2)


Now, assume we say "take revision r1 of package B". Then the obs
computes merge((B, r1), (A, r5), (A, r13)) which conflicts - that's
the current state of things.

Now we/the obs could traverse back to find the "last working merge".
If we do so, we find merge((B, r1), (A, r5), (A, r11)), which is OK.
But hmm... if we look at our timeline we have t(A, r11) > t(B, r2).
That is, in reality we probably never saw/checked out these merged
sources.

Ok, so our next strategy could be: find the last working merge
before (<=) t(B, r2). This is merge((B, r1), (A, r5), (A, r9)), which
is OK. Now, we have t(A, r9) < t(B, r2), but does this imply that we
have ever seen/checked the corresponding sources? This is unlikely,
for instance, if (A, r10) was committed immediately after (A, r9)
(that is, 0 <= t(A, r10) - t(A, r9) < eps, for some small eps > 0).

Another issue with this strategy is that the commit times might not
be strictly monotonically increasing. In the worst case, all commits
were done at the same time(stamp) (for instance, this can happen if
all commits where done by a script (to a local obs)). In this pathological
case we end up with the drawbacks of our first strategy.


Remark:
Hierarchy can make this revision finding a bit more involved. For instance,
if package A is branch instead of a plain package and A's branch target C
is also a branch, we have to first find the correct expanded revision of C
etc.


Summary:
- automatically picking *some* working revision is probably not the
  smartest idea (you might have no idea what you actually submit)
- finding the "correct" revision can be cumbersome
- maybe we could provide a hint in the help text(s) that
  "osc buildhist"/whatever might be a good starting point for finding the
  revision?


Does this "clarify" my previous my a bit?


PS: sorry for this lengthy mail...

**Comment by marcus-h** [comment]
Hmm the timeline visualisation looks broken in a browser. Maybe it
is easier to grasp if you copy it to some text file...
