### ISSUE TITLE
osc setlinkrev should leave a message in the log

### ISSUE THREAD

**Issue by johanneskastl** [openSUSE/osc#470]
Triggering a `osc setlinkrev` leads to a new revision in `osc log`, but leaves no hint where this revision has come from and what generated it.

I would suggest that `osc setlinkrev` leaves a message like "setting link revision to foo", or anything else that would explain what that commit does, without digging through diffs.

Currently `osc setlinkrev` does not accept a `-m` option, so no message can be given by the user.

**Comment by marcus-h** [comment]
On 2018-11-19 00:36:30 -0800, Johannes Kastl wrote:
> Triggering a `osc setlinkrev` leads to a new revision in `osc log`, but leaves no hint where this revision has come from and what generated it.
> 
Hmm yes.

> I would suggest that `osc setlinkrev` leaves a message like "setting link revision to foo", or anything else that would explain what that commit does, without digging through diffs.
> 
> Currently `osc setlinkrev` does not accept a `-m` option, so no message can be given by the user.
> 
Are you interested in submitting a PR? :) (I'm just asking since you
submitted some PRs in the past;) )

The changes are quite "trivial":

- core.set_link_rev has to be adapted:
  * add a message/comment parameter to the function def
  * when doing the http_PUT a "comment" query parameter has to be
    part of the url

If you also want to add a new "-m/--message" option to the "setlinkrev"
command, the commandline.do_setlinkrev method has to be adapted:
- add a new option
- pass that option to core.set_link_rev

That's it:)
