### ISSUE TITLE
--offline flag does not work

### ISSUE THREAD

**Issue by sebix** [openSUSE/osc#560]
On TW 20190514 with osc 0.165.0:
```
$ osc build -o
Failed to reach a server:
 [Errno -2] Name or service not known
```

**Comment by lethliel** [comment]
Can you please provide the output of

`osc --http-full-debug build --offline`

offline mode works fine for me with osc-0.165.0

**Comment by sebix** [comment]
Sure:
```
$ osc --http-full-debug build --offline


-- GET https://api.opensuse.org/build/home:sebix:intelmq:unstable/openSUSE_Tumbleweed/_buildconfig
Failed to reach a server:
 [Errno -2] Name or service not known
```

**Comment by lethliel** [comment]
Thanks. Now I can reproduce this. I needed to disconnect my connection to get this error.

This is the problem (which is in the code since commit b16f1c9c):
https://github.com/openSUSE/osc/blob/8b56405d1077899f92aa17c4f50bbbe105e00317/osc/commandline.py#L6094

This needs to be changed to the same logic as in build.py where the already local buildinfo and buildconfig files are used.
