### ISSUE TITLE
osc vc -F doesn't add a leading dash anymore

### ISSUE THREAD

**Issue by krop** [openSUSE/osc#670]
`osc vc -F <somefile>` works differently since a recent update.
Before, it was adding a dash before the file content. It doesn't anymore.

Our script to prepare the KDE releases writes changelog entries into files for each package then run `osc vc -F /path/to/somepackage.changes`

Before it was adding a dash before the first line, now osc doesn't anymore. (https://build.opensuse.org/request/show/746310)

The only relevant change I can think of is:

> Transfer the name of the input file to vc instead of the content (obs-build/vc will do the rest and open the file).

**Comment by lethliel** [comment]
Hi. This is indeed a regression. Can you please provide an example of your somepackage.changes file?

I will try to come up with a fix today. But I am on a training.

**Comment by krop** [comment]
> Hi. This is indeed a regression. Can you please provide an example of your somepackage.changes file?
> 
Sure:
`# cat attica.changes `

> Update to 5.64.0
>   * New feature release
>   * For more details please see:
>   * https://www.kde.org/announcements/kde-frameworks-5.64.0.php
> - Changes since 5.63.0:
>   * Use ECMGenerateExportHeader to manage deprecated API better
>   * Add some std::move in setter functions

**Comment by lethliel** [comment]
The following patch fixes the problem:
https://paste.opensuse.org/63721289

Can you please apply this to /usr/lib/build/vc? 

I am not sure if this is the right way. (best solution) But for the moment this fixes your problem.

**Comment by krop** [comment]
Indeed, the issue disappears with this change

**Comment by lethliel** [comment]
I was thinking about this. 
The old behavior was a bug (prepending a '-'). This should only be done when the -m switch is used: 

`vc -m 'My new version' tool.changes`

This will result in

`- My new version` in tool.changes

When using `osc vc -F my_new_changes tool.changes` calls: 

`vc tool.changes my_new_changes`

and just prepends whatever is in my_new_changes.

So the new behavior without prepending is correct and whatever creates `/path/to/somepackage.changes` needs to be adapted. 

Otherwise we will break the original behavior of `vc <changes_file> <content>`

@adrianschroeter @marcus-h Can I please have your opinions on this?

**Comment by lethliel** [comment]
@krop Thanks for the fix in your toolset. This can be closed then.
