### ISSUE TITLE
clean/remove /home/abuild before every build

### ISSUE THREAD

**Issue by mslacken** [openSUSE/osc#873]
Sometimes old configurations from previous builds pop as /home/abuild is just partly cleaned before a new build.
So I propose to remove/clean the complete /home/abuild directory before a build, not just remove /home/abuild/rpmbuild
As workarround one can use '--clean', but this costs always some seconds before a build.

**Comment by marcus-h** [comment]
On 2020-11-26 13:33:48 +0000, Christian Goll wrote:
> Sometimes old configurations from previous builds pop as /home/abuild is just partly cleaned before a new build.
> So I propose to remove/clean the complete /home/abuild directory before a build, not just remove /home/abuild/rpmbuild

Hmm this sounds like a fix/workaround for a specific package - I'm not
sure if there's something we can do from the osc/obs-build side. For
instance, if we remove /home/abuild by default another user might complain
that she cannot reuse her /home/abuild/expensive_computation file anymore
between two consecutive builds. Yet another user might request to also
delete a /tmp/xxx file because her build fails if this file is present
etc.

> As workarround one can use '--clean', but this costs always some seconds before a build.
>
IMHO, --clean is the way to go. I guess you want to "save" some time
during debugging, right? If so, what about adding the specific cleanups
to the %prep section of your spec file (of course, just for the debugging
phase...)?

**Comment by dmach** [comment]
I also think that `--clean` is the way to go.
If it doesn't work as expected, please open an issue in [openSUSE/obs-build](https://github.com/openSUSE/obs-build).
Osc should only call `build` with appropriate options rather than (re-)implementing its functionality.
