### ISSUE TITLE
osc 0.171: regression when calling 'osc service lr download_files'

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc#874]
since upgrading to osc 0.171, the command `osc service lr download_files` no longer executes the service (and files are not being downloaded as expected)

I tested locally by reverting to osc 0.170-2.2 (last published version in Tumbleweed before upgrading to 0.171) and `osc service lr download_files` immediately started working again.

I'm assuming this to be related to https://github.com/openSUSE/osc/commit/894b97d471066e5935b3178bf525379f4545d29c

I tried:
`osc service run download_files` => no files being downloaded
`osc service manualrun download_files` => no files being downloaded
`osc service localrun download_files` => no files being downloaded
`osc service disabledrun download_files` => this variant works (but feels less obvious than an explicit 'localrun' execution

**Comment by DimStar77** [comment]
I tested it with a package that does not actually have a _service file, but where we rely on the implicit download_files execution to get the files as specified in the spec file.

e.g.

```
osc co openSUSE:Factory/proftpd
cd openSUSE:Factory/proftpd
rm proftpd-*.gz*
```

and then the various service run usages (users were used to `osc service lr download_files`

Interesting observation: `osc service lr source_validator` is running

**Comment by marcus-h** [comment]
On 2020-11-27 09:34:11 -0800, Dominique Leuenberger wrote:
> since upgrading to osc 0.171, the command `osc service lr download_files` no longer executes the service (and files are not being downloaded as expected)
>
Yes, we fixed (yes, it is really a fix:) ) "osc service <mode>
<single service>" (see commit cb6eaf3720fdd5206c2bc06d7bf444c6fdd14ecb
("Fix single service disabled run")).

marcus@linux:~> osc cat openSUSE:Factory _project _service
<services>
  <service name="format_spec_file" mode="localonly" />
  <service name="download_files" mode="disabled" />
  <service name="source_validator" mode="localonly" />
</services>

marcus@linux:~>

Previous osc versions ignored the "mode" in case of a single service run
(it also ignored potential parameters). That's why localrun executed a
service with mode "disabled". Now, both bugs are fixed - that's why
"localrun" does not execute the download_files service anymore. IMHO,
the new behavior is much more sane but unfortunately it breaks your
existing "workflow":/

You can run the download_files service via "osc service disabledrun
download_files".

**Comment by DimStar77** [comment]
It's terrible for a user having to figure out if a given service happens to be disabled in any of the lines projects u might build against .. especially the new manualrun would be really expected to actually do as asked.

Or a 'reallyrunnomatterwhatiwantitnow' 😏

**Comment by marcus-h** [comment]
On 2020-11-27 13:30:37 -0800, Dominique Leuenberger wrote:
> It's terrible for a user having to figure out if a given service happens to be disabled in any of the lines projects u might build against .. especially the new manualrun would be really expected to actually do as asked.
>
> Or a 'reallyrunnomatterwhatiwantitnow' 😏
>
That's what "runall" does: "osc service runall download_files" runs all
download_files services regardless of the mode.

**Comment by DimStar77** [comment]
ok, runall does work indeed;'run' should also work according to the description though:

```
    run         r  run defined services with modes "trylocal", "localonly", or no mode set locally, may take an optional parameter to run only a
                   specified source service. In case parameters exist for this one in _service file
                   they are used.
```

'no mode set locally' I would interpret as in the _service file (what I as user, without deep knowledge ofOBS setup, can investigate)

It's all a bit confusing - the 'wrong'mode with the bug felt more intuitive :)

**Comment by bnavigator** [comment]
But `runall` and `run` only runs services actually enabled in `_service`. IMHO `localrun` should still consider `download_files` as active, if the package has **no own _service file**. The command is advertised as such in the [wiki](https://en.opensuse.org/openSUSE:OSC).

**Comment by mcepl** [comment]
> IMHO `localrun` should still consider `download_files` as active, if the package has no own service file.

Did you test it?
```
$ osc service disabledrun download_files
```
runs for me even in the package directory without `_service` file.

**Comment by bnavigator** [comment]
yes `disabledrun` works. But not `localrun`, which is still advertised in the wiki. Either adjust that or re-enable download_files by default.

I actually didn't bother to set up an alias yet. Just typing the whole command every time I need it.

**Comment by mcepl** [comment]
You know, that it is a wiki, right?

**Comment by bnavigator** [comment]
I know but I would rather keep the localrun command working instead of chaning to "disabledrun", which is counterintuitive IMHO.

**Comment by adrianschroeter** [comment]
IMHO download_files should be either in manual or localonly mode. 

localonly would be prefered here, because it would validate the sources by default on local operations. However, that requires that the download_files service is good enough with validating already existing files to avoid unnecessary slowdown due to re-download.

I will have a look, if we can improve download_files to make this working.

We could even go with trylocal then, where the sources gets validated local, but the server would also validate to ensure that it has happened.

**Comment by adrianschroeter** [comment]
The improvement for download_files is coming here: https://github.com/openSUSE/obs-service-download_files/pull/28

**Comment by dmach** [comment]
This seems to be fixed already, closing.
