### ISSUE TITLE
`osc build --vm-type kvm` - qemu: could not open kernel file '/boot/vmlinuz': No such file or director

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/osc#882]
I am trying to find secure solution to test local builds. KVM asks for root permissions and fails, because of missing `/boot/vmlinuz`. There is no such file on my Fedora 33, and I am not sure what it is needed.

```
$ osc build xUbuntu_20.10 bleachbit.dsc --vm-type kvm
...
[    9s] cycle: dh-autoreconf -> debhelper
[    9s]   breaking dependency debhelper -> dh-autoreconf
[    9s] done
[    9s] cp: -r not specified; omitting directory '/home/abiroot/p/home:andrew_z/bleachbit/_transformed'
[    9s] booting kvm...
[    9s] Using UART console
[    9s] /usr/bin/qemu-kvm -nodefaults -no-reboot -nographic -vga none -cpu host -object rng-random,filename=/dev/hwrng,id=rng0 -device virtio-rng-pci,rng=rng0 -runas qemu -net none -kernel /boot/vmlinuz -initrd /boot/initrd -append root=/dev/sda rootfstype=ext3 rootflags=data=writeback,nobarrier,commit=150,noatime ext4.allow_unsupported=1 mitigations=off panic=1 quiet no-kvmclock elevator=noop nmi_watchdog=0 rw rd.driver.pre=binfmt_misc console=ttyS0 init=/.build/build -m 512 -drive file=/var/tmp/build-root/xUbuntu_20.10-x86_64/img,format=raw,if=none,id=disk,cache=unsafe -device ide-hd,drive=disk,serial=0 -drive file=/var/tmp/build-root/xUbuntu_20.10-x86_64/swap,format=raw,if=none,id=swap,cache=unsafe -device ide-hd,drive=swap,serial=1 -serial stdio -chardev socket,id=monitor,server,nowait,path=/var/tmp/build-root/xUbuntu_20.10-x86_64/img.qemu/monitor -mon chardev=monitor,mode=readline -smp 4
[    9s] qemu: could not open kernel file '/boot/vmlinuz': No such file or directory
[    9s] No buildstatus set, either the base system is broken (kernel/initrd/udev/glibc/bash/perl)
[    9s] or the build host has a kernel or hardware problem...

The buildroot was: /var/tmp/build-root/xUbuntu_20.10-x86_64/.mount
```

**Comment by marcus-h** [comment]
On 2020-12-13 06:31:23 -0800, Anatoli Babenia wrote:
> I am trying to find secure solution to test local builds. KVM asks for root permissions and fails, because of missing `/boot/vmlinuz`. There is no such file on my Fedora 33, and I am not sure what it is needed.
>
You have to provide a kernel + initrd that can be used for booting
the KVM. For instance, for openSUSE:Factory, we provide a special
kernel-obs-build package that provides a /.build.kernel.kvm and a
/.build.initrd.kvm file, which is automatically used by the obs-build
script (see the kernel-obs-build.spec file in the
openSUSE:Factory/kernel-obs-build package).
AFAIK, such a special kernel package does not exist for xUbuntu 20.10.
Hence, you have to manually provide a kernel + initrd via the
"build-kernel" and "build-initrd" config options.

osc config general build-kernel /path/to/your/kernel
osc config general build-initrd /path/to/your/initrd

You could try your currently running kernel.

**Comment by abitrolly** [comment]
That's too deep. :D

Well, there are some `vmlinuz-5.9.11-200.fc33.x86_64` in /boot - are there any problems if the tool could discover and use them?

/boot/vmlinuz-5.9.11-200.fc33.x86_64

**Comment by marcus-h** [comment]
On 2020-12-13 10:21:28 -0800, Anatoli Babenia wrote:
> That's too deep. :D
>
> Well, there are some `vmlinuz-5.9.11-200.fc33.x86_64` in /boot - are there any problems if the tool could discover and use them?
>
Hmm we already have the /boot/vmlinuz heuristic... I'm not sure
what additional heuristics we could use/make sense (maybe using
the running kernel?). But that's something for obs-build [1].

> /boot/vmlinuz-5.9.11-200.fc33.x86_64
>
Are you able to boot the KVM with this kernel?

[1] https://github.com/openSUSE/obs-build

**Comment by abitrolly** [comment]
> Are you able to boot the KVM with this kernel?

Don't want to risk rebooting my system. Too many open tabs to deal with. Maybe in a few days.. I will try.

**Comment by marcus-h** [comment]
On 2020-12-13 16:43:17 -0800, Anatoli Babenia wrote:
> > Are you able to boot the KVM with this kernel?
>
> Don't want to risk rebooting my system. Too many open tabs to deal with. Maybe in a few days.. I will try.
>
Huh?! There is usually no need to reboot your system.

**Comment by abitrolly** [comment]
> Huh?! There is usually no need to reboot your system.

Yes. But I am not sure how it works, and don't want to risk. I know that standard QEMU uses full emulation, so nothing bad may happen, except that I can run out of mem. With KVM I am not sure how those two kermels will interact with each other and CPU.

**Comment by abitrolly** [comment]
Funny enough. After writing this report I switched to another session with Ctrl+Alt+F2 just to see that I've lost GNOME there. Looks like it is Wayland crash (https://github.com/systemd/systemd/issues/17965) and there is no way to recover my windows, so I will have to reboot anyway.

**Comment by abitrolly** [comment]
> osc config general build-kernel /path/to/your/kernel
> osc config general build-initrd /path/to/your/initrd

While I was writing this my kernel already updated, and updating global option doesn't seem like a long term solution.
```
$ cat /proc/cmdline
BOOT_IMAGE=(hd0,msdos1)/vmlinuz-5.9.13-200.fc33.x86_64 root=UUID=bbfba948-01d2-40e2-a3fb-5bec00295f8d ro rhgb quiet
$ osc config general build-kernel /boot/vmlinuz-5.9.13-200.fc33.x86_64
$ osc build xUbuntu_20.10 bleachbit.dsc --vm-type kvm
```

**Comment by abitrolly** [comment]
Now there is no `/boot/initrd`.
```
...
[    2s] qemu: error reading initrd /boot/initrd: Failed to open file “/boot/initrd”: open() failed: No such file or directory
[    3s] No buildstatus set, either the base system is broken (kernel/initrd/udev/glibc/bash/perl)
[    3s] or the build host has a kernel or hardware problem...
...
$ ls -ls /boot
total 214148
  224 -rw-r--r--. 1 root root   226796 Nov 23 21:37 config-5.9.10-200.fc33.x86_64
  224 -rw-r--r--. 1 root root   226825 Nov 24 21:31 config-5.9.11-200.fc33.x86_64
  224 -rw-r--r--. 1 root root   226825 Dec  8 18:56 config-5.9.13-200.fc33.x86_64
    4 drwx------. 3 root root     4096 Jul 27 20:28 efi
    4 drwxr-xr-x. 2 root root     4096 Oct 11 14:30 extlinux
    4 drwx------. 6 root root     4096 Dec 14 14:41 grub2
60012 -rw-------. 1 root root 61448775 Aug  5  2017 initramfs-0-rescue-c3b1f5b205ed4158bd61c304044f4bb7.img
33532 -rw-------. 1 root root 34332989 Nov 26 16:16 initramfs-5.9.10-200.fc33.x86_64.img
33540 -rw-------. 1 root root 34337673 Dec  5 11:26 initramfs-5.9.11-200.fc33.x86_64.img
33576 -rw-------. 1 root root 34378890 Dec 14 14:21 initramfs-5.9.13-200.fc33.x86_64.img
    4 drwxr-xr-x. 3 root root     4096 May  2  2018 loader
   16 drwx------. 2 root root    16384 Aug  5  2017 lost+found
 5244 -rw-------. 1 root root  5369426 Nov 23 21:37 System.map-5.9.10-200.fc33.x86_64
 5244 -rw-------. 1 root root  5369812 Nov 24 21:31 System.map-5.9.11-200.fc33.x86_64
 5244 -rw-------. 1 root root  5369849 Dec  8 18:56 System.map-5.9.13-200.fc33.x86_64
 7128 -rwxr-xr-x. 1 root root  7295064 Aug  5  2017 vmlinuz-0-rescue-c3b1f5b205ed4158bd61c304044f4bb7
 9928 -rwxr-xr-x. 1 root root 10165200 Nov 23 21:37 vmlinuz-5.9.10-200.fc33.x86_64
    4 -rw-r--r--. 1 root root      167 Nov 23 21:34 .vmlinuz-5.9.10-200.fc33.x86_64.hmac
 9928 -rwxr-xr-x. 1 root root 10164336 Nov 24 21:31 vmlinuz-5.9.11-200.fc33.x86_64
    4 -rw-r--r--. 1 root root      167 Nov 24 21:29 .vmlinuz-5.9.11-200.fc33.x86_64.hmac
10056 -rwxr-xr-x. 1 root root 10295792 Dec  8 18:56 vmlinuz-5.9.13-200.fc33.x86_64
    4 -rw-r--r--. 1 root root      167 Dec  8 18:54 .vmlinuz-5.9.13-200.fc33.x86_64.hmac
```

**Comment by abitrolly** [comment]
I tried to use `initramfs` as `initrd`.
```
$ osc config general build-initrd /boot/initramfs-5.9.13-200.fc33.x86_64.img
$ osc build xUbuntu_20.10 bleachbit.dsc --vm-type kvm
```
It reset the terminal and freezed, so I had to kill it after 2 minutes.
```
[  OK  ] Started Show Plymouth Boot Screen.
[    4s] [  OK  ] Started Forward Password R…s to Plymouth Directory Watch.
[    4s] [  OK  ] Reached target Paths.
[    4s] [  OK  ] Reached target Basic System.
keyboard interrupt, killing build ...
could not kill build in /var/tmp/build-root/xUbuntu_20.10-x86_64/img, kvm instance is dead already
interrupted!
```

**Comment by abitrolly** [comment]
Trying to use files from https://build.opensuse.org/package/show/openSUSE:Factory/kernel-obs-build

**Comment by abitrolly** [comment]
Had to download `kernel-obs-build-5.9.14-1.2.x86_64.rpm` manually (because auth).
```
$ bsdtar xfv kernel-obs-build-5.9.14-1.2.x86_64.rpm
x ./.build.hostarch.kvm
x ./.build.initrd.kvm
x ./.build.kernel.kvm
```

**Comment by abitrolly** [comment]
And these didn't work. Again, the terminal is reset and after some SeaBIOS screen there is now.
```
[  !!  ] Failed to execute /sbin/init
```
![image](https://user-images.githubusercontent.com/8781107/102083695-098ed600-3e25-11eb-9fa3-9f2d43ab736d.png)

**Comment by marcus-h** [comment]
On 2020-12-14 12:57:36 +0000, Anatoli Babenia wrote:
> And these didn't work. Again, the terminal is reset and after some SeaBIOS screen there is now.
> ```
> [  !!  ] Failed to execute /sbin/init
> ```
Hmm works for me:
- osc getbinaries openSUSE:Factory kernel-obs-build standard x86_64
- cd binaries
- rpm2cpio kernel-obs-build-5.9.14-1.2.x86_64.rpm | cpio -i
- adjust build-kernel and build-initrd config options
(*) - patch build script
- cd openSUSE:Tools/osc
- osc build --vm-type kvm xUbuntu_20.10 x86_64 osc.dsc --clean

=> build starts

You can try to add the "--clean" option when running "osc build ..."

(*): I always have to patch the build script so that /dev/hwrng is not
     used - I did not investigate it further so far (but from a quick glance
     this does not seem to be a problem in your case)

--- a/build-vm-kvm
+++ b/build-vm-kvm
@@ -231,7 +231,7 @@ vm_verify_options_kvm() {
     fi

     if test -n "$kvm_rng_device" ; then
-        if test -c /dev/hwrng &&
+        if test -c /dev/hwrng.DOESNOTEXIST &&
            test -f /sys/class/misc/hw_random/rng_current &&
            test "$(cat /sys/class/misc/hw_random/rng_current)" != none; then
             rng_dev="/dev/hwrng"

**Comment by abitrolly** [comment]
That didn't work. The full log is attached.

[build.log](https://github.com/openSUSE/osc/files/5689286/build.log)

**Comment by marcus-h** [comment]
On 2020-12-14 06:16:58 -0800, Anatoli Babenia wrote:
> That didn't work. The full log is attached.
>
Hmm hard to tell... The only obvious difference I see is that in your
case the image is created via virt-make-fs (but I don't think this is
a problem...).
It probably boils down to debug why the "/usr/bin/qemu-kvm -nodefaults ..."
call fails. It fails with "Failed to execute /sbin/init". The question
is why it tries to execute /sbin/init at all because we specified
"init=/.build/build".

> [build.log](https://github.com/openSUSE/osc/files/5689286/build.log)

**Comment by abitrolly** [comment]
@marcus-h no idea. I don't see any SELinux warnings either.

**Comment by marcus-h** [comment]
On 2020-12-15 04:52:21 -0800, Anatoli Babenia wrote:
> @marcus-h no idea. I don't see any SELinux warnings either.
>
Hmm is SELinux enabled on your system?

Can you check if the /.build/build script really exists in the image?
For this, mount the image via

mount /var/tmp/build-root/xUbuntu_20.10-x86_64/img /mnt

and check if /.build/build exists (for instance, via
"ls -la /mnt/.build/build"). Afterwards, "umount /mnt".

If the file exists, you can try to manually run the following command:

/usr/bin/qemu-kvm -nodefaults -no-reboot -nographic -vga none -cpu host \
-object rng-random,filename=/dev/random,id=rng0 \
-device virtio-rng-pci,rng=rng0 -runas qemu -net none \
-kernel /home/abiroot/p/osc/.build.kernel.kvm \
-initrd /home/abiroot/p/osc/.build.initrd.kvm \
-append "root=/dev/disk/by-id/virtio-0 rootfstype=ext3 rootflags=data=writeback,nobarrier,commit=150,noatime ext4.allow_unsupported=1 mitigations=off panic=1 quiet no-kvmclock elevator=noop nmi_watchdog=0 rw rd.driver.pre=binfmt_misc console=ttyS0 init=/.build/build" \
-m 512 -drive file=/var/tmp/build-root/xUbuntu_20.10-x86_64/img,format=raw,if=none,id=disk,cache=unsafe \
-device virtio-blk-pci,drive=disk,serial=0 \
-drive file=/var/tmp/build-root/xUbuntu_20.10-x86_64/swap,format=raw,if=none,id=swap,cache=unsafe \
-device virtio-blk-pci,drive=swap,serial=1 -serial stdio \
-chardev socket,id=monitor,server,nowait,path=/var/tmp/build-root/xUbuntu_20.10-x86_64/img.qemu/monitor \
-mon chardev=monitor,mode=readline -smp 4

This is the same command as executed by the build script except a different
rng is used (/dev/random instead of /dev/hwrng) (I can hardly imagine that
this yields a different result, though).

Originally, the second line was
-object rng-random,filename=/dev/hwrng,id=rng0 \

If this still results in the same error, you can try to play
with the value of the "-append" option. Maybe specify init=/bin/bash
and check if this works.

What you could also try is the following hack and see what happens:

mount /var/tmp/build-root/xUbuntu_20.10-x86_64/img /mnt
ln -s /.build/build /mnt/sbin/init
umount /mnt

Next, run the qemu-kvm command again.

**Comment by abitrolly** [comment]
> Hmm is SELinux enabled on your system?

Fedora 33 comes with enabled SELinux. 

> mount /var/tmp/build-root/xUbuntu_20.10-x86_64/img /mnt

I could only mount this with `sudo`.
```
$ sudo mount /var/tmp/build-root/xUbuntu_20.10-x86_64/img /mnt
$ ls -la /mnt/.build/build
-rwxr-xr-x. 1 root root 47193 Dec 10 15:24 /mnt/.build/build
$ sudo umount /mnt
```

**Comment by abitrolly** [comment]
> If this still results in the same error

The same error.

> Maybe specify init=/bin/bash and check if this works. 

With that there no more `/sbin/init` error. Instead it shows this.
```
groups: cannot find name for group ID 0
I have no name!@localhost:/#
```

**Comment by abitrolly** [comment]
> What you could also try is the following hack and see what happens:

The same.
![image](https://user-images.githubusercontent.com/8781107/102718628-2f6f1b80-42fa-11eb-9aa6-f8b2b565d0a7.png)
```
sudo mount /var/tmp/build-root/xUbuntu_20.10-x86_64/img /mnt
sudo ln -s /.build/build /mnt/sbin/init
sudo umount /mnt
```

**Comment by dmach** [comment]
Closing as this doesn't seem to require any osc change.
The problems come from kernel-obs-build and the build environment in general.
