### ISSUE TITLE
local build with osc and remote obs build fail in different manner

### ISSUE THREAD

**Issue by slowphil** [openSUSE/osc#886]
I'm trying to debug a build failure in OBS for Debian_Testing and xUbuntu_20.10 releases, but when I try to build locally with osc it fails while setting up the build environment, whereas in OBS the compilation goes through and the error occurs in "make tests". In my previous experience, building failures were always identical for local or remote builds. 
The same problem was already [reported in the mailing list](https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/thread/HDP2VOKQKDUJICBOA4UQ4IOHKC7FATKK/) a few weeks ago, not by me, but for the same project. 
It seems the local build environment is not being created in the same way on my system and remotely, but I do not know where to start to resolve that issue. I even wonder whether I should report here or in obs issues.
I'm running osc on Debian testing; my distro is up-to-date and the osc and obs-service-* deb packages (taken from OBS) too.

**Comment by slowphil** [comment]
I realize that for the same project, when building locally for xUbuntu_18.04 it fails at "configure", while it goes through remotely on OBS.

**Comment by marcus-h** [comment]
On 2020-12-30 15:58:06 -0800, slowphil wrote:
> I'm trying to debug a build failure in OBS for Debian_Testing and xUbuntu_20.10 releases, but when I try to build locally with osc it fails while setting up the build environment, whereas in OBS the compilation goes through and the error occurs in "make tests". In my previous experience, building failures were always identical for local or remote builds.
> The same problem was already [reported in the mailing list](https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/thread/HDP2VOKQKDUJICBOA4UQ4IOHKC7FATKK/) a few weeks ago, not by me, but for the same project.

I just replied [1] to the thread.

> It seems the local build environment is not being created in the same way on my system and remotely, but I do not know where to start to resolve that issue. I even wonder whether I should report here or in obs issues.

That's probably a VM based build vs. chroot based build issue. You
can also perform a VM based build locally. Something like

osc build --vm-type kvm ...

should do the trick.

[1] https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/message/3HNASEVAXHHGKEIEJ4EDG7TDS2ORAAOO/

**Comment by slowphil** [comment]
Thank you for the fast reply, for explaining the issue and for providing solutions!

The workaround you gave in the mail thread, involving using "order", allows to perform  non-vm builds, indeed. That unblocks me.
 
However, adding  --vm-type=kmv by itself is not sufficient, because there is a failure when booting the kvm: 

> [   11s] booting kvm...
[   11s] Using UART console
[   12s] /usr/bin/kvm [...] -kernel /boot/vmlinuz [...]
[   12s] qemu: could not open kernel file '/boot/vmlinuz': No such file or directory

I note it's not the same filename in OBS workers, so maybe I am supposed to provide that file somehow... Is the use of kvm in OBS documented somewhere?

**Comment by marcus-h** [comment]
On 2021-01-01 10:25:04 -0800, slowphil wrote:
> However, adding  --vm-type=kmv by itself is not sufficient, because there is a failure when booting the kvm:
>
> > [   11s] booting kvm...
> [   11s] Using UART console
> [   12s] /usr/bin/kvm [...] -kernel /boot/vmlinuz [...]
> [   12s] qemu: could not open kernel file '/boot/vmlinuz': No such file or directory
>
> I note it's not the same filename in OBS workers, so maybe I am supposed to provide that file somehow...

Hmm yes, you have to provide a kernel+initrd that can be used by KVM
(for openSUSE targets this works "out of the box" because a special
kernel-obs-build package is installed into the VM which provides
a kernel that is automatically used during "osc build ...").

What you can do is the following:

- get the current kernel-obs-build rpm

$> osc getbinaries openSUSE:Factory kernel-obs-build standard x86_64

- unpack the rpm

$> rpm2cpio binaries/kernel-obs-build-5.10.3-1.2.x86_64.rpm | cpio -iv

(note that the files are extracted into $PWD and start with a ".")

- configure the kernel+initrd for a KVM based build

$> osc config general build-kernel $PWD/.build.kernel.kvm
...
$> osc config general build-initrd $PWD/.build.initrd.kvm
...
$> osc config general build-type kvm
...

Next, run "osc build ..." again.

(Note: it is not required to use the kernel+initrd that are provided
by the kernel-obs-build package - you can also use a custom kernel
(as long you can boot the VM with it).)

> Is the use of kvm in OBS documented somewhere?
>
Hmm no idea:/ Maybe have a look at [1].

[1] https://openbuildservice.org/help/

**Comment by dmach** [comment]
Using `--clean` is probably the best option here.
The cleanup is not done in osc, but in [build](https://github.com/openSUSE/obs-build), please open an issue with them if you want to make the proposed change.
