### ISSUE TITLE
pypi artifact is outdated

### ISSUE THREAD

**Issue by chenrui333** [openSUSE/osc#893]
👋  it looks like the pypi artifact (is still with 0.167.2) is not the latest release, `v0.172.0`, just want to call it out. Thanks!

**Comment by marcus-h** [comment]
On 2021-01-27 12:34:23 -0800, rui wrote:
> 👋  it looks like the pypi artifact (is still with 0.167.2) is not the latest release, `v0.172.0`, just want to call it out. Thanks!
>
Hrm. The travis log [1] states

"Skipping a deployment with the pypi provider because this is not a tagged commit"

which is probably my fault:/ What I did is the following:
- update NEWS file + version in core.py => commit
- create 0.172.0 (lightweight) tag
- update version in core.py => commit
- push --follow-tags
- realize that --follow-tags only works for annotated tags
- push --tags

The problem is probably that the HEAD of the master branch was
never associated with a tag and, hence, travis did no deployment
(but that's just a guess).

Unfortuantely, I have no clue how to fix that without doing a
new release (which I want to avoid) :/


[1] https://travis-ci.org/github/openSUSE/osc/jobs/756409360

**Comment by chenrui333** [comment]
I think the tag build is always failing, here is [some example build](https://travis-ci.org/github/openSUSE/osc/builds/742699939)

```
error: could not restore untracked files from stash
The stash entry is kept in case you need it again.
PyPI upload failed.
failed to deploy
```

**Comment by chenrui333** [comment]
You can technically rerun the the tag build on travis UI (or you can also debug build by sshing to it), there is no need to create another tag.

**Comment by chenrui333** [comment]
Any update on this thread?

**Comment by dmach** [comment]
I've manually uploaded the latest 0.x version: https://pypi.org/manage/project/osc/release/0.182.0/
