### ISSUE TITLE
Please expand defines in updatepacmetafromspec command

### ISSUE THREAD

**Issue by stoecker** [openSUSE/osc#932]
In perl packages we use following:
```
%define cpan_name Net-MQTT-Simple
URL:            https://metacpan.org/release/%{cpan_name}
```

Now osc updatepacmetafromspec results in
```
...
<url>https://metacpan.org/release/%{cpan_name}</url></package>
....
````
but that's not the real usable URL.

**Comment by marcus-h** [comment]
On 2021-07-22 01:40:06 -0700, Dirk Stöcker wrote:
> In perl packages we use following:
> ```
> %define cpan_name Net-MQTT-Simple
> URL:            https://metacpan.org/release/%{cpan_name}
> ```
>
> Now osc updatepacmetafromspec results in
> ```
> ...
> <url>https://metacpan.org/release/%{cpan_name}</url></package>
> ....
> ````
> but that's not the real usable URL.
>
Hmm yes... we could call the "spectool" script from the build/obs-build
package for querying the URL. Perhaps, we could extend the spectool
script so that it also read sections (like %description). Then,
we could get rid of the broken spec file parsing in osc.
